name: "LFTP deploy action"
description: "Deploy a set of files via LFTP (supports FTPS)"
inputs:
  host:
    description: "Host to connect to"
    required: true
  port:
    description: "Port used by the host"
  username:
    description: "login username"
    required: true
  ssh_private_key:
    description: "The private key for authentication to connect your server"
    required: true
  ssl_verify_cert:
    description: "Should the host's x509 SSL certificate be verified"
    default: true
  ssl_force:
    description: "Should SSL be manditory (prevents non TLS/SSL fallback if HELO said it was an option)"
    default: false
  ssl_priority:
    description: "Cipher priorty string to pass to gnutls. (Set to 'NORMAL:%COMPAT:+VERS-TLS1.0' if you need compat)"
    default: ""
  mirror_args:
    description: "Additional arguments to pass to LFTP mirror command"
  local_path:
    description: "the local path to upload from the deployment repo"
    required: true
  remote_path:
    description: "the path to upload the files to on the remote host"
    required: true
  max_retries:
    description: "the maximum number of sequential tries of an operation without success"
    default: 1
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "upload-cloud"
  color: "green"
